"""Prompt templates live here."""

from prompts.agent_prompts import ANALYST_SYSTEM_PROMPT, EDA_SYSTEM_PROMPT, RESEARCHER_SYSTEM_PROMPT
from prompts.sql_prompts import SQL_GENERATOR_SYSTEM_PROMPT, SQL_REPAIR_SYSTEM_PROMPT

__all__ = [
    "ANALYST_SYSTEM_PROMPT",
    "EDA_SYSTEM_PROMPT",
    "RESEARCHER_SYSTEM_PROMPT",
    "SQL_GENERATOR_SYSTEM_PROMPT",
    "SQL_REPAIR_SYSTEM_PROMPT",
]
